# Generated by Django 3.2.3 on 2021-05-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NameRemember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('contacts', models.CharField(max_length=255, null=True)),
                ('how_met', models.TextField(max_length=2555, null=True)),
            ],
        ),
    ]
